### ISSUE TITLE
CeCILL license

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-blocks-my_external_backup_courses#1]
Same as with the other plugin you submitted into the plugins directory, all traces of the CeCILL license should be removed and GPLv3 should be exclusively used.

**Comment by cperves** [comment]
No more cecill

**Comment by mudrd8mz** [comment]
Thanks. Can you please remove it from the Description field at https://moodle.org/plugins/view/block_my_external_backup_courses too?
