### ISSUE TITLE
Direct SQL injection of the configuration parameter

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-blocks-my_external_backup_courses#2]
The way how the `search_roles` has to be defined, and then how it is directly injected into the SQL query is ugly, prone to cross-db incompatibility and potentially dangerous. It would be much better if the config itself was supposed to hold plain comma-separated list of role names without quotes. That one should then be converted into array via PHP `explode()` and then `trim()` applied to each element. The resulted array should then be used in conjunction with `$DB->get_in_or_equal()` before used in the SQL query.

**Comment by cperves** [comment]
made
I'll pay attention to that kind of practise in the future
Thanks
