### ISSUE TITLE
Avoid usage of eval()

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-blocks-my_external_backup_courses#3]
The current way how the `external_moodles` setting is considered to be a valid PHP code that is evaluated and then used to populate the array is ugly, non-moodley, prone to misconfiguration typos that lead to fatal consequences and potentially dangerous.
It should be replaced with a plain text format setting from which the needed array would be populated. For example, something like comma-separated list (or maybe space-separated or whatever that suits the given usage) that is simple to be parsed.

**Comment by cperves** [comment]
made with simple chain
Question (for an other plugin I made) : would ajax object format (without direct code evaluation) would be convinient in complicated case?

**Comment by mudrd8mz** [comment]
If by "ajax object format" you mean JSON, then yes, it is preferred - although I am not quite sure about usability for admins.
