### ISSUE TITLE
Missing prefix for locallib functions

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-blocks-my_external_backup_courses#5]
See the section 'Namespace collisions' in https://docs.moodle.org/dev/Plugin_contribution_checklist - your locallib.php defines function in the global PHP scope without the frankenstyle prefix. Either rename them, or wrap them as static methods of correctly names utility class to avoid potential collisions.

**Comment by cperves** [comment]
made with block prefix
Thanks for the advice, I prefer static class but to much impact in that case
